### ISSUE TITLE
Does not handle bin

### ISSUE THREAD

**Issue by tlvince** [bahmutov/have-it#12]
If a package defines a [bin](https://docs.npmjs.com/files/package.json#bin) (executable) `npm` will symlink it under `./node_modules/.bin`. Currently `have-it` doesn't handle these, which means `npm run` scripts aren't supported (amongst other things).

**Comment by bahmutov** [comment]
yeah, need to discover those and create "proxy" bins

**Comment by bahmutov** [comment]
Version `1.12.0` has been published to NPM. The full release note can be found at [have-it/releases/tag/v1.12.0](https://github.com/bahmutov/have-it/releases/tag/v1.12.0).

**Tip:** safely upgrade dependency have-it in your project using [next-update](https://github.com/bahmutov/next-update)
